language: objective-c
install:
  - bundle install
  - brew outdated carthage || brew upgrade carthage
script:
  - ./Scripts/ci.sh
matrix:
  include:
  - osx_image: xcode11
    env: ACTION="swift-package";SDK="iphonesimulator";DESTINATION="platform=iOS Simulator,OS=13.0,name=iPad Pro (12.9-inch) (3rd generation)"
  - osx_image: xcode11
    env: ACTION="swift-package";SDK="appletvsimulator13.0";DESTINATION="platform=tvOS Simulator,name=Apple TV"
  - osx_image: xcode11
    env: ACTION="swift-package";SDK="macosx10.15";DESTINATION="platform=OS X"
  - osx_image: xcode11
    env: ACTION="swift-package";SDK="watchos6.0";DESTINATION=""
  - osx_image: xcode11
    env: ACTION="xcode";SCHEME="Valet iOS";SDK="iphonesimulator";DESTINATION="platform=iOS Simulator,OS=13.0,name=iPad Pro (12.9-inch) (3rd generation)";XCODE_ACTION="build test"
  - osx_image: xcode11
    env: ACTION="xcode";SCHEME="Valet tvOS";SDK="appletvsimulator13.0";DESTINATION="platform=tvOS Simulator,name=Apple TV";XCODE_ACTION="build test"
  - osx_image: xcode11
    env: ACTION="xcode";SCHEME="Valet Mac";SDK="macosx10.15";DESTINATION="platform=OS X";XCODE_ACTION="build test"
  - osx_image: xcode11
    env: ACTION="xcode";SCHEME="Valet watchOS";SDK="watchos6.0";DESTINATION="";XCODE_ACTION="build"
  - osx_image: xcode11
    env: ACTION="carthage"

  - osx_image: xcode10.2
    env: ACTION="xcode";SCHEME="Valet iOS";SDK="iphonesimulator";DESTINATION="platform=iOS Simulator,OS=12.2,name=iPhone X";XCODE_ACTION="build test"
  - osx_image: xcode10.2
    env: ACTION="xcode";SCHEME="Valet tvOS";SDK="appletvsimulator12.2";DESTINATION="platform=tvOS Simulator,name=Apple TV";XCODE_ACTION="build test"
  - osx_image: xcode10.2
    env: ACTION="xcode";SCHEME="Valet Mac";SDK="macosx10.14";DESTINATION="platform=OS X";XCODE_ACTION="build test"
  - osx_image: xcode10.2
    env: ACTION="xcode";SCHEME="Valet watchOS";SDK="watchos5.2";DESTINATION="";XCODE_ACTION="build"
  - osx_image: xcode10.2
    env: ACTION="pod-lint";SWIFT_VERSION="5.0"
  - osx_image: xcode10.2
    env: ACTION="carthage"

  - osx_image: xcode9
    env: ACTION="xcode";SCHEME="Valet iOS";SDK="iphonesimulator";DESTINATION="platform=iOS Simulator,OS=11.0,name=iPhone 7";XCODE_ACTION="build test"
  - osx_image: xcode9
    env: ACTION="xcode";SCHEME="Valet tvOS";SDK="appletvsimulator11.0";DESTINATION="platform=tvOS Simulator,name=Apple TV";XCODE_ACTION="build test"
  - osx_image: xcode9
    env: ACTION="xcode";SCHEME="Valet Mac";SDK="macosx10.13";DESTINATION="platform=OS X";XCODE_ACTION="build test"
  - osx_image: xcode9
    env: ACTION="xcode";SCHEME="Valet watchOS";SDK="watchos4.0";DESTINATION="";XCODE_ACTION="build"
  - osx_image: xcode9
    env: ACTION="pod-lint";SWIFT_VERSION="4.0"
  - osx_image: xcode9
    env: ACTION="carthage"
